apiVersion: v1
kind: Secret
metadata:
  name: minio-auth
  namespace: data-storage
type: Opaque
stringData:
  rootUser: ENC[AES256_GCM,data:ITrkWSRQGhsF2eI=,iv:ihbeFFxg/PLcB+7RI6y+5JxQdOr7TNB1yGUNgCJCWko=,tag:Q9UvLbSjv83IMwkDWwr/Yg==,type:str]
  rootPassword: ENC[AES256_GCM,data:dbxGhw+h+vssRKMoVZrc,iv:GAfuOaNch71Z4XQLk3Fx9vOVnzFEIn3F73UIDnwmy5w=,tag:hMpZ6WuT9e2gQR7Ezu8HHQ==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSFVLQUlXZWtPbkF0U3cw
        eVIzREZDTTR0WndMVWRIekF1bVhJcmpNb1NnCm92OTM2T2I5WVJQZTh4S2hPeC9p
        UUJvbEpDZ3luMDZRbGRjdUw2TXAyRDQKLS0tIGRPVDMxR0pLTHVtekNzYUg2K2p5
        V01ZL2toZkVqMHBUR2MvUHd6bHdxM28KPZ866YqXrAk07dex6KhN44r7lz/kH2ex
        BO0Ozgn7PsbJ2J4IefTUArVz3TJR/lbpnT3ABF02ek6iThGYLLOEhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T10:40:15Z"
  mac: ENC[AES256_GCM,data:iVUFWh0YmSlIZpv1UdIZLwgtvFJf6lscuACtw6BmrUNMhehuHgaoFlxnLsiJtwbzV0I2XRJgNUDSGPIe003jnDsuLwEHhep6TspgYKQ0sYeQEd7EmuNo2cDt9IfpIUgmbWeFWk3rf9+SJFTebkzRJP7t8KZHoV+9UwlPFHEyctg=,iv:AtTNAq5X8CuIkkPF3xq0IXxeN5FRVMv4GJoH7pWTsIA=,tag:1dUA1J9hrCG3PcswqbVXtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
