apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgres-auth
  namespace: data-storage
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:H1lG76s=,iv:oM1VNmjF5CeiiOqhSBMQ22/M05p6opR8ENWKyYa+yVk=,tag:uD+T7Z8qV9m3xywhu8NGgw==,type:str]
  password: ENC[AES256_GCM,data:b1vifJWs2YcHWNPoFfPi,iv:6iKnTDPzMkG4adSXEwPW8WYXrRxQN5weNOfhzLBr+Qw=,tag:KL/n+lDlDICD2oshGbjj2Q==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsblVOUVl0bjExbW00bzNx
        Rk5nb1h2cW1GcTBhMyt2dEVTSUdBbFpnWlg0CmFwbXJWOEZnSFh1aEdITUlvNG4r
        ckdyTDlJd1ZlV2JXaGUwdTQwWVVTOWsKLS0tIGRmVjZvRnIzRjB5aVpVMVRiQ0w2
        bXBOUU1CbVo0ZWhMZ2tQUklTSXN1OEEK2B+v/BDTpqe9wgy8+CazO3WOL2xVTuAH
        tDM5Dya7RRHhVWcEUniqr/wM4a6XBIlPG1xP6kSo+eBIeEUgfP5U9w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T11:03:07Z"
  mac: ENC[AES256_GCM,data:3KDPfh2B24a2leU7EfbhMk9EpVhN/mXdMHOEHq/AGmUpZVtgHnMGYyjLuUsBOiHky5fKcoBOxpui1djEUv4TMmQV2laiB8Kdn6pe++9dbZCJaUTzh0yMFckAChoQSLkS3S/RR7vF1pW7j5taiqwOAWxKH3ymvp1HxflnX4Ffcm8=,iv:9VckYEPmeLerUWdXwts/cTCF4na7cBkks+ev88a5lU4=,tag:wh7uhxmJO2NOgHHG3Irqwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
