apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-events
  namespace: argo-events
spec:
  interval: 10m
  releaseName: argo-events
  targetNamespace: argo-events
  install:
    createNamespace: true
  chart:
    spec:
      chart: argo-events
      version: "2.4.5"
      sourceRef:
        kind: HelmRepository
        name: argo
        namespace: argo-events
  values:
    controller:
      metrics:
        enabled: true