apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-events
  namespace: argo-events
spec:
  interval: 10m
  releaseName: argo-events
  targetNamespace: argo-events
  chart:
    spec:
      chart: argo-events
      version: "2.4.5"
      sourceRef:
        kind: HelmRepository
        name: argo
  install:
    createNamespace: true
  values:
    # Standard reicht i.d.R.
    # Falls du RBAC/CRDs Probleme bekommst: sag Bescheid, dann pinnen wir explizit die CRDs-Optionen.
    controller:
      metrics:
        enabled: true