apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepo-argo.yaml
  - helmrelease-argo-events.yaml
  - eventbus-default.yaml
  - secret-argo-events-minio.encrypted.yaml
  - rbac-argo-events-to-workflows.yaml
  - eventsource-minio-input-data.yaml
  - sensor-ml-pipeline-on-csv.yaml