apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgres-credentials
  namespace: mlflow
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:eo3/E2zA,iv:si5Qk9dKxtTOn+e7uDWWUCeQhQePd7kSzBm2IZ1uTGU=,tag:C89KgiAqH5M/bT/aoHhTUg==,type:str]
  password: ENC[AES256_GCM,data:/5JSTLOvhjzerkFyzU2a,iv:t5zIIIPZGpEfQx9RiEm151XwgbK65ftLgaT4eMelGFg=,tag:nTgs6TySBqt/aH4N8sOchw==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDd0hXZlduUjY1Um93cytz
        U1FuZ1N4bDg2Yi8xcks3MTVNYi9yUkNudXpJCndVdnVSZVV2VVB6cm1VTEVZeTVh
        bGw1OEEwWFA1bzdINjdaTmMydElabncKLS0tIGl0SDRmZDIzalJLdWc5cnlLSkNw
        R1kwcVFBTXFXUVcxVUxrVzlxVjJ0MEEKFfthk0zi7p4giwRtfhdcVID3lysn3UiK
        6rBFS6bptkxvUAWkAJbcWqacmUa/Rj2pw5bIZGe5ctCikw23NCXEdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T14:36:28Z"
  mac: ENC[AES256_GCM,data:zPyMv6QukgIUuuIOzhrpgf0feho4qPq7lPG/8biCW9cPtCEVLMCbwbzN0+fwH/s5RfheXnrpc2v1mZnMoRKRwY1VUGk9kfjL+7h5eS0iEihxcKn20M3DeQWvQDuycYU+ABZOtwgoY0/OTpFz49yd7poXsiMnmyeSjl4MYyW3s/Q=,iv:+A1unS04bvVa44201cRA05lyj9r4YDqLxhoegltFi5I=,tag:cWdmsJMHnmU1YuEO4SwSnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
