apiVersion: v1
kind: Secret
metadata:
  name: mlflow-s3
  namespace: mlflow
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:YDjYw9J0,iv:dSSiZxqupLTaiLBAyVM1YW5bbWQv/YDgDuiFzZrOkgs=,tag:VnkNgnq9HmF9SDJzg1Q5ZA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AEysnn/zqdm+/MKQsiw=,iv:WOz7qFtgTv9irDnOUMOdf+I0CqTFIxucZ/oGSlEEgRQ=,tag:6jpQw0bVYFlVbT4iZQe8gw==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNdk9aa296N05WdENRcDdT
        cWRYMFEwaWN5MDNBMW93ekpnbWxqNG8rd3hzClpweENhenNWS1JlNVFyUWpJZzFM
        MGNyd3h2bU56b1lwNmJvM2VTbU9Cc1kKLS0tIEVTMGxJNnMvQ1B1dnBCTGN2eE4w
        OHhhUnJYa3kxR2t4Szk0dERySit3K3cKgY4fjey6WlLJovMisYTHEPAKSdmV7+XV
        AHdCsdAXKE/HoIWp3ejFWUlu9iWPqU0A7fI1SR+Gyo5LNkGNjYJOJg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T11:52:05Z"
  mac: ENC[AES256_GCM,data:p9cYfbXx8TFClwEYlvLdsP6J99/S42x+Qx2Oqou2hbtRc7zBM5Wtm7pkAr24xDGqcolC/sTRXPU9yUQf5DBRvmBqU7em1RaHHi4g3bZ/aP6LuV6OWqeXx+S72BcDhDbLzprqUIYBQUrjwVRhuyEj8u4y2wsT5l+Ti5ODDUlpud8=,iv:KWKvKFAOLtXxsppm1oiZI3qGRgn80YGNGmFk8XEWYLs=,tag:iMYcvAN3fRDc5qrPbF+P8w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
