apiVersion: v1
kind: Secret
metadata:
  name: mlflow-postgres-credentials
  namespace: mlflow
type: Opaque
stringData:
  DB_PASSWORD: ENC[AES256_GCM,data:HMwyaXme1obzCNsjR+hI,iv:oMXsBbvXNnRpsh7CSL7wIrYV5vE2le4Pw4cWC8tvqbE=,tag:7uKOhGfcx8JuzPN8iKkWUQ==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySXpxWkk5YTlSdkpxaDlZ
        cjdwZ0I3VnV4K3Ewcit4YUMxU3dTOHVZVXcwCnBVbHg1d2N2VW9aNDJPR0s0aEp6
        dUF2eXdodVB1bUVvemFoU3VNRG15OG8KLS0tIHErSENKeEtVQWZ1WjI0SnN6NE5n
        YWtCQmFEK3VpQTE5N1RZM1ZsR25SV1EKIs7FWay0EPNU1MRH8BnNi4vlTvj8qQ3+
        75eUeW06QqO8bP9YKaMXOtc+qS02hveavEbOojF+pgFUultWa3AxPA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-19T11:51:40Z"
  mac: ENC[AES256_GCM,data:vfCMMDTJJSb9sf2rNgZNzcuR1FKeYKeE1M2HzYkFnn/9L07i17WCDT4FRS2zKpkBfsOA+2OnYtwMdGDDT/1GYqK7NTRzNNWkZyip4PNN7G6ZM1aWJO58KDCqGQKqRiW/VWsxkB1HQhgZ/QU4PYrfdcC52Co9JMtUFk83nH4daAc=,iv:2m8vmTpEMetkBDgohMhwsWCNysedS23UF2J5q/5Hg+k=,tag:I4UZ3A3ZL1hz+vcmGOhCng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
