apiVersion: v1
kind: Secret
metadata:
  name: argo-events-minio
  namespace: argo-events
type: Opaque
stringData:
  accessKey: ENC[AES256_GCM,data:WiLC9VX+,iv:m1ufv04+1yjmJdh2ZM26DmoaO2GtRyYLPOujU3s6y0o=,tag:vzPNHV5iXj43RQMf5VZv6Q==,type:str]
  secretKey: ENC[AES256_GCM,data:7lsCtJ9IaFCJfCvKxHc=,iv:YypaSbAZiW85e/KvTowOP47gsN8AVEvsvTZ7PDcA3Ow=,tag:xwklL47kblLr/bTN4UGkFQ==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNDhWZ3lQWHJmUjdqeDM0
        QUQxZ1ErL2U1TWp1K0JENzRYK3dWUGF3cWdzClZyWUJwVWkya1d2QzNxYkxLWGl3
        QUVPbG1ISEdlMHlMdWJ4aW1lOHBjN28KLS0tIG0xTklDZVlqUFc1ZmtwbnoyTVl1
        ODJOMHdyT1Noa3FRQ0NlMmdqRVd1akkKy8XK0wjKF+Ca8T27vlU8me9PWCmjsPaI
        ru+z/jGe3ii4unuI3vhwmbkZFZILs5FFKFvu3REFo649o96xPVXO3Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T14:44:08Z"
  mac: ENC[AES256_GCM,data:UZ0OvQTOxbXvbpaPi9KRhXVsHLOha98MpCSxZc2bMyC3BG75jO/8szd4LV0fG8id2/WJS5NzfuzhZkwR5v4tXuOhOGKZZ5slonNevOpg+YtppA8sy0Ag771jKhRzBjewiFBsxuQXDdV45+f+cTEV2RpnGLMMBcBn0SF4EfNaxiE=,iv:9VL0RF+aYhOXU7A8RocrJm1c16d1kruYDqGo3zNPBjA=,tag:ZSDykadr82hSz9APYssuLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
