apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: data-storage

  chart:
    spec:
      chart: minio
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
      interval: 1h

  install:
    createNamespace: true
  upgrade:
    cleanupOnFail: true

  values:
    mode: standalone

    # --- Images: auf GHCR umstellen (global + konkret) ---
    global:
      imageRegistry: ghcr.io
      security:
        allowInsecureImages: true
    image:
      registry: ghcr.io
      repository: bitnami/minio
      # nimm erstmal wieder r3, weil Bitnami h√§ufig so taggt
      tag: "2025.7.23-debian-12-r3"

    console:
      image:
        registry: ghcr.io
        repository: bitnami/minio-object-browser
        tag: "2.0.2-debian-12-r3"

    auth:
      existingSecret: minio
      rootUserSecretKey: rootUser
      rootPasswordSecretKey: rootPassword

    persistence:
      enabled: true
      storageClass: local-path
      size: 10Gi
      accessModes:
        - ReadWriteOnce

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hostname: minio.group-jsti.dski23a.timebertt.dev
      extraTls:
        - secretName: minio-tls-cert
          hosts:
            - minio.group-jsti.dski23a.timebertt.dev

    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hostname: console-minio.group-jsti.dski23a.timebertt.dev
      extraTls:
        - secretName: console-minio-tls-cert
          hosts:
            - console-minio.group-jsti.dski23a.timebertt.dev
