apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: data-storage
type: Opaque
stringData:
  #ENC[AES256_GCM,data:cavqiXrEUIti,iv:Ov9H45rtMZuWcwXy06pUAoAVnWmu4GPPiDnOwHC9Dww=,tag:pbASOJxJY6rlBXzA1gwbXw==,type:comment]
  rootUser: ENC[AES256_GCM,data:IEPtEsFGJBCRUQ==,iv:zmovny+paADV5I5nKOu+a1O/iG/BUbCtVmrqkkaDCE4=,tag:jxWHDRLy00PHUNHjPxSteg==,type:str]
  #ENC[AES256_GCM,data:ZHUg1j8cDSYf,iv:JaupqvGHX1F+qq4uX5AcAw8aBfjDiEBVMLpLW5ZP9Lg=,tag:MCmtImn/C8cOe+nmGIe8MA==,type:comment]
  rootPassword: ENC[AES256_GCM,data:qJZhK9GBRU+zUSxrSUAkqBhgBjcBWeksZrI=,iv:qzkAvrznPEVpgRxSC8wdtlJbcPsVyu2SHh12WsKWbl0=,tag:veqwlCXzsJCCuSrtpOD1mQ==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbjBMRndPRTgwOUNOdTBw
        Z2ZKTUN4TDlFMkhVUlJHTlRMaGRZQXRpRXpFCkRzZVRBajVtMnZXOU8yUkNFcUZ6
        USszdDROSG10bUZZV3F6WFdJZ1hqTVkKLS0tIFBQRUlJYWRkU3paaU44anMydkVJ
        elNGTnl0UThHaFBySGlJWnFOVFQ0WGMKtdoX+2Z8O8OKmMlE790mLP0d/ZyHDngE
        tSN1TifeuUdDi2MxRSBnwuoK6xc0LQRGgESI4ZwiRX0AJbDV8/iC3A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T17:18:00Z"
  mac: ENC[AES256_GCM,data:uDdxP/NLMdO7LmaNW6preGyoFEDt6z93oM35UfSichOxc2DtCciYZBLnc2T5ySryNBlF495CvjshCQSrzkKPPOrl/qhgMWFjt84TJsB0M6v3iNTirn3GrjSG7awD+Gp/J/nNsii2mtMqEbLkkj5C2sbTqy4tsFSqsd/ZCPhsYBs=,iv:M9PCblcCMChh+dTWrxmK+ifqW7mc9ldPwkWm5MP39cQ=,tag:mFZSJOOFfb5LGoVvKnp3NA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
