apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: data-storage
type: Opaque
stringData:
  rootUser: ENC[AES256_GCM,data:AQiB8k3nAD1ygw==,iv:a69LoIZhiOPeNbhg0iAGzjZytgSdFJEgc4+knbPtN3I=,tag:CJWnbIjzYsWVdcSJ90CsRA==,type:str]
  rootPassword: ENC[AES256_GCM,data:ICY8AA+ICyBc0MQjNJd2Mqqi8OfNSUIMcpY=,iv:ybTpzOCru5hkuig56cijNIkCfbYXHIgjru4Ikc7JHIQ=,tag:MdOPcsQO8N2+yHVBiO3rPA==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWnc5dUpiS00wMDRsRlV4
        M29xc2Z1UnFnT0NEWG5tZzllN3ZFWEZLcEdBClNLOVRyY25YVkc5WkhSMFlUSHph
        S1I0YmF6aTNoRW1SQ0dTREFqNlRvSEkKLS0tIDY3VmZuckFEcmlZcHh5R0NSbWpJ
        TUlicnZlVFBVR1Y0dDQvYnl4b09iYmcKUCiS1ZsFch8st2NokW/jdCzbFWBk9UVR
        /kHekFoBn1vOLv3OQS0EwWpFPqvCJ7NWPhVwgF2132PfAey8FUOoVQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T17:05:29Z"
  mac: ENC[AES256_GCM,data:6iikdBgQRxwL+VkkorpZhWHCNGhy5gieZv96saHOWXzUhxoaYhxtdP/xG9Jnqt6EDjeGGFZRmp4oM5iHSzrQXSTpAVMgpdsRycQROskANBzTKzmTYtxT8hxw32sckL+Qrf+BNq2Hlmv5v5fKiP06pwt4m7Gfvb9NjfK8MAUgdF4=,iv:xWxeIyYjJ1dH1yxsPMKcZ/2MkaMs8r5WyEJ5dW6g/2M=,tag:9LyowVC0YarEgR1ML/EQrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
