apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: data-storage
type: Opaque
stringData:
  rootUser: ENC[AES256_GCM,data:9x7gMNUklIeYZg==,iv:lKAwSOq/HTxxa5W9CoVMXcF1cRAkxL743mGwBjPEAWM=,tag:S6qmj9UUCUgDHFNyUN/IDQ==,type:str]
  rootPassword: ENC[AES256_GCM,data:62m+ALg9kz0sXfEwLjcA6ugeGgPnYSd0gck=,iv:+z3D3hWUr8FpO1hjifgPpU4+Aq3cpbYqE6boTaJQB60=,tag:xfoEBnbJOXR2+T0CA+/HkA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age13trtw82hqsmyfqn6s3du406dgh5zu0es6j3xuzgsqsaynq9dxvhsq0ysj9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZS9VS01POHQwMWw1VXdu
        QnRTYXBhRy9UK1hjQnlHY3ZLUnpScm11NUFZCmwwTGVRZ2dYTEdycnUrL1hKMEVQ
        VjIzZURFdHZkWE5NZElLN0d5RS9KY0UKLS0tIEd0K1RwN1M2R3B4Y0hZUUVFRGFV
        a2VtK3kxYndRZytXTEdMMG14cUNmZVUK+RdvTyGm491twVZ17VMyliq42xuZBbQG
        deTaj1dx11PcC/7MlQBatKHWVon3cr+8fi/idSc11v15DRvzLvT0lA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-18T16:43:57Z"
  mac: ENC[AES256_GCM,data:657K8XjlVEiMp5Hb6mZOWUKaa3CuScZ86dl5j2l5uHgHrqe2P3Ij3irO8Q1q6QVfpmWVTIJrmL5PjJRETU8qpdRWx7C7cwZWvpu/eYr6+A4ucpOVS6mzUnI5e7CdJya2VcjCeHbwsRacIZ3GzSxl2xi0IdwXvN2mlL/gWvHw3as=,iv:QK8OWZsTgcuthcQZy6MSOa6+0Mmu+xPm/f6xoZGolO4=,tag:S8L4xGgvv0heh5ralVvwAQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
