apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrepo-jupyterhub.yaml
  - helmrelease-jupyterhub.yaml
  - ingress-jupyterhub.yaml
  - secret-jupyterhub.encrypted.yaml
