apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-auth
  namespace: jupyter
type: Opaque
stringData:
  dummy-password: ENC[AES256_GCM,data:iDn4MeI=,iv:RhGe4mktie4aVacFfEmq8T5AfbslDBmWi3wTWv7YCm0=,tag:rtfJg9tcazoTFAYHFNLz3w==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMkI5VmdrNzdtakVweEdm
        d01vZHVKTXJ1dS96Rk5xbklrWGxRRlJBNlFNCjRrU0RsUFl0TEYrNmdOQzQ0RzhT
        V3pJdlNQTmU5TFZvalRoVDNJSWp6Z1UKLS0tIEhTVkJaMEpmcG96OGhFQWxwS1NN
        ZmR0TkllTE8xODV1bHZFRGhxVWJSdXcKdEbldmh0TaPZIWpY7MU0uA+CUxE8hCwT
        F33jFN9Zxw4MHd445nGlcuS0N6gw+ryVUMm/CemosyHUqoW+VMgvvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T09:59:27Z"
  mac: ENC[AES256_GCM,data:wgG3Z5dhJC4rQtyNBai7VUDTy6SE2p158RakaJ1ThJ04yl1AhOeK7W3rRYDnhQfFy566NQNcAGtOAzmzy7/YeuB1HhtPOdfDVDlIkIKYTDiCfr+NCm4BxPYVQeIenRNoPZ2DuW+0f+WKNnnofEDIvySjvOP9ugni/hu5iyzzwUg=,iv:gB1i1VssTIvR6Dk2QYgimti0niZixZRO/K9l0DMMqt8=,tag:Zc+AFXlAl1EGVjNepgH9zA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
