apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-s3
  namespace: argo-workflows
type: Opaque
stringData:
  accesskey: ENC[AES256_GCM,data:64sb/f0vxX/jAg==,iv:oG7TD6q3mF1b9h4G6xXXmM8+f9guaYN4Hcmj2ZqQwkA=,tag:DQOCa3hckW3Na7bvkYne7Q==,type:str]
  secretkey: ENC[AES256_GCM,data:MxlVvVoeaZa26j40Sfzb,iv:s7wbl6x+UTfowAePpPd3lQQ3vb9roHCWNFsn0uSMl+A=,tag:dD0b6k1d2NuBQTly+f3viw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8CN26l2OE0nRiw==,iv:2bjYsPIRRP/f7o1FMn4WJ5JiTCOUJIZssGSn3CtSxK0=,tag:yY8be3B6XpyQGCV4U07PpA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3APJ+GkBkf+kJ9+YJb6IdlFNgdimclOcuYc=,iv:KbQ5+KxcdDBp4qz2B5GO+kqmrEx2scKQNxr02ucf5pA=,tag:48rCXPofBmF15iplz3dAhQ==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:t2bxffDL0GLM,iv:08eDFDZsHx9p6KdPx0hVd9YivwAFUXYXY6fJOEw5TfM=,tag:VKRtP5+vceVQ2OY1rjZcXw==,type:str]
  MLFLOW_S3_ENDPOINT_URL: ENC[AES256_GCM,data:VQK7DF7x7hkiwPuV7L2dsteOvFAEiqd6kFU+7l9z5U/4eu1WEOZfji/9o4hhFXr2,iv:QUO99vqAXDQHVXNx+8ClkQ6UCMKE5jKJGoH4fj7kVUc=,tag:qoqgKgv9UNunx7Tx1JLCpA==,type:str]
  MLFLOW_TRACKING_URI: ENC[AES256_GCM,data:SbMmGl2KGdsZCJdY24VhQ1rjaU9pMtuAxfYQF1vd0RI9AJhrf7c=,iv:NxfxPu/5hgTKQNtQQXxLHt/rMHRu/8q9rqIfTS1RNqs=,tag:wKdYw44MbK7iqsBo8xGneQ==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eG9WV0Z1dHVKeEh5bU1t
        VjZuUG94NTMwd1dQRUsveWMrUjlLQ3Blb2pJCm1TVDFxZFQ3OGJ0cWNtZ0l5aUI3
        SVRRdUY5aWRtYnFndkNNU1NnUGhkc0UKLS0tIHVWSHV4clJNNmk4UklNQURhbmN2
        a2tacjFVSU04aU05TXpzdlc0T2FzVGMKwIN4oLOR8f8c4rxAGT34I820wHM3aG6c
        vV/k+QboU2Sq1wxQuBfVznirxsbO8VjPhsgUCDt+nujxkUS77hjyLA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T13:32:12Z"
  mac: ENC[AES256_GCM,data:7TPdKXeXuLc45q2KfyLADO8BuyDr0q2J1h+T8DjT5t73mgPu80VwDabRM91LrsWfsjgLSRiYbJmoltGPi0KWmp1SBwbSKQtZ3qDvCPVKseqn9Uf0HMHQhCE/1Xm7cL+COiNl6alPaqxQGWuYNDEir66GHPOVFu8KWDuQ8QXm3MU=,iv:JrBEz6OJi64EwI5SOc6+NCrySKUZ1s73iR2NYQc3ezE=,tag:XusMMjDUzZV55PINnJ1cOQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
