apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-s3
  namespace: argo-workflows
type: Opaque
stringData:
  #ENC[AES256_GCM,data:Us+psYd60sJOi6JznsjLCbxDOW0hf9Y+2xQU6Cs=,iv:FU1WiRmKovG0ERoLxF4Duo/FKnQ1we5X6HQUroprkA8=,tag:zWaXoz8lSUlK5HrfzrpMAQ==,type:comment]
  accesskey: ENC[AES256_GCM,data:HZxpDUhR,iv:Ur6WpDIf4SMAWgG9GcDv0bBxI5GABTyUhI0sqt5JmsM=,tag:jkKW+7MDWtuDmoah6qmfPg==,type:str]
  secretkey: ENC[AES256_GCM,data:VqIlma8S7b7evxT8WKo=,iv:v6EVPPZEydQnIldZ3BvBGGfFKU2wbDFj9pq2kIr2Ivc=,tag:1HlfCaO8LWxsp+ovgV+dWg==,type:str]
  #ENC[AES256_GCM,data:NZIOPf/fRbFUJposUoqZSNEaw3bTjyNUt9WgKHv1DP49mag=,iv:3zjyooEuRSywgzznwQVk0J8iZ3JFF3XCl3UclvlmqZo=,tag:WQYFuuZ1FkH1YBLBTTwfnw==,type:comment]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:nof/RNmp,iv:ZQgp4B6hfVCTfO4E4HJmXTJzupgsx/pz0hwku2EUP6U=,tag:opie4FbrnKgvK8r+o8zUPA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:VSvGjDsQenNla8B4GG8=,iv:WTRHhBmxSEeVWnc9IDWZodFeqJzEwC8my12BW6LE780=,tag:dokfBAwAjRFm9uWhZVJVGg==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:hpuXaCKrFDtT,iv:FTkEj/WlWbC01ZeVLzn6tNTpe43/AGJjBm7ANuI5be4=,tag:N8NbXsSGyViZV52eUJalMQ==,type:str]
  MLFLOW_S3_ENDPOINT_URL: ENC[AES256_GCM,data:l1CLo85/gHA3z30lfEEkLyp1dsxm3yGMBB0GRnkTX05A+9+BbeK85M0duIprorLB,iv:eKST3+5ze08n0fe6SETxcn9fA8GN19eFV+rvr2sbQK0=,tag:zEnyMAH8ePB/9m9tvmjd9A==,type:str]
  MLFLOW_TRACKING_URI: ENC[AES256_GCM,data:vToEGVoU8DEZiuIb78k7qig3vLuLTlQ/BdCtsFxT6NdklT6bi2c=,iv:KLYuFritjLDml+vKdCSttUe4rdpgzX9A66p8Jf9zs8U=,tag:9nuXKOFjymksmiTvq8noIg==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMnJEeEd1dTkxWGNnOWkz
        eWl3RUxhengwV1NIQW9xWkFONXdhaVhqZm1zCi9UaUx3T3JmY3hJOEdNdUNzSVpF
        cGFNMC9yQ1RidmZyQi9WTkIzbGZxUWMKLS0tIGM1ckNQdTRFcjJhMEN1NWtJSHRv
        ejE1UTdKTWMzZXBqenROMXBiazNoVmcKqcbCa2iQiRhZZf9fM+BV6ylARxDP5zcQ
        wIkpTTKOI5qctokgh/Q8vfDII8bAGbuWWT5SrCr0hbiIBMP7FZJ+Ew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T13:53:27Z"
  mac: ENC[AES256_GCM,data:WTrSDRT1lgzKgMva2/E0ftRlv4ZzdKXkkKyeUXS9oNrF+lFm6aGK0RyJC9HfA2ebvHLaWgeCGm/+SlHcS58RMcs1P3ZV+UxlWQ2KvDKgg4wrjRAgoWkr+JMPJfy4cpEDL8sA78iV08eapaYzgBY2BdeCKnV/7pAJBOIg9LVtE0g=,iv:oYDAHAHqhyVd5dG1+KTaCoAp60VZOq6vbtfO0BnFY6E=,tag:bGcYTEoBJFq3o0ZXgfX9rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
