apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-s3
  namespace: argo-workflows
type: Opaque
stringData:
  accesskey: ENC[AES256_GCM,data:JP51ev15grTjbg==,iv:wD5+JYIo/LdwRg2LRPOTYo43FD2sN4j54IL6hDxL0QQ=,tag:PJB+Re94kpm86PHV3Fl2nQ==,type:str]
  secretkey: ENC[AES256_GCM,data:ExxZqOC+/qGAerzmoO/QfU1cS/8PzYauS+8=,iv:EIkybWzQCYdQOhpBmgzlQAnIxZPvrmT0v1Fwyc1KOlY=,tag:QdjgoztCxFw69jhjSRDf1w==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iFd/p3JJYwmQQQ==,iv:Kaa2j2MOxe2uFb/9NMYiCv1fJoeTZ9+eXvkTSYaalsA=,tag:thJZGhUAn6GpO48koGSjTg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xpOO23amQ5XnQKVwMXaJuxm8KtaKxkyaVXU=,iv:3aKon7Yat6S9n4cOBoZAvOyLdUrZx14DL7GflOjzsSU=,tag:IwNT184ZjNVmqaJSfssYag==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:2LQsCqTwatBW,iv:Fx91ArUEhrXLi3QnBO5jrRVZfElOIPQET/jPBsLkmkA=,tag:1gMx0mIFJ0+yAdeyajTQkg==,type:str]
  MLFLOW_S3_ENDPOINT_URL: ENC[AES256_GCM,data:70FGuZgdqXj3KO+k5ukPV7d21TssXNjHtEU+AmijuR1CcU28qkGWr6cIZ/KBwhFH,iv:4rdymLtHwlrauwos9kBjxI2JktGhI0dWTdO0h0hZJtw=,tag:epdf5fPO+8nu7d8E+uRlPg==,type:str]
  MLFLOW_TRACKING_URI: ENC[AES256_GCM,data:4IWDGPeSl1fealUoAf5RxiHv3MkYRNMyxkIxpGswkG+pa2HiwAg=,iv:3jxEh89Xf036PM4xu3UkKzcOC1FISxhEXku9/vrqQfg=,tag:Ykm8om1FlUKdX2Y5Wf4QYg==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RTdROE53RDZkbFd5QnZG
        SVRnd1o0UDd4UDN2c0VheGNUY0srb1paUFVVClh1cWdQV3FXZU42Z29kSnVPRkxk
        WkFXNEtXcUYyT2RMdjhHc1BGYXF0QWcKLS0tIENZQkZLejJUWk1jR2xyV1h4NUJ4
        bC9xc3lrQ2VaSlVtZWpUSDZUTm1HcFEK9ACzv0Q9wkHChtAKS3l+tUBFIjogik/H
        uLK+Jlz7Bsa4CxFm8Vvv5RSyJ/6hgqHCOzWe9UnvZeeLV5iEZvz0wg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T13:46:04Z"
  mac: ENC[AES256_GCM,data:ofo5x5jR9lAZnaziVkZHSLLfYw3etBM5YK6/Yx0ptKgUiwfetJNJtcSZ144PSNkM+iPjKmMU8nc37YUlnqbUY7jtmqTi2GHcCNWuDDHZkJcNZHfaAdB+CJ277qjaz0vfggiTBXTbVKwUQMiseJRIF2IjDtWRooWMUsij3HQCmvI=,iv:bvk2Iq1acVnTX1RdaUYfqsk39pDl4u+KpbLK4JOXFew=,tag:WeVEddxMhF5A9b/YFeVljg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
