apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-s3
  namespace: argo-workflows
type: Opaque
stringData:
  # Für Argo artifactRepository
  accesskey: "mlflow"
  secretkey: "<MINIO_SECRET_KEY>"

  # Für MLflow in deinen Python Steps
  AWS_ACCESS_KEY_ID: "mlflow"
  AWS_SECRET_ACCESS_KEY: "<MINIO_SECRET_KEY>"
  AWS_DEFAULT_REGION: "us-east-1"
  MLFLOW_S3_ENDPOINT_URL: "http://minio.data-storage.svc.cluster.local:9000"
  MLFLOW_TRACKING_URI: "http://mlflow.mlflow.svc.cluster.local"