apiVersion: v1
kind: Secret
metadata:
  name: argo-artifacts-s3
  namespace: argo-workflows
type: Opaque
stringData:
  accesskey: ENC[AES256_GCM,data:0a3spJ4sCabopQ==,iv:W8rkN+OPzWYPzMUSr+VF7I9mUNnic470NHXBdCAwZ7M=,tag:O6llVWVslPVCnl/89ECK1w==,type:str]
  secretkey: ENC[AES256_GCM,data:1ZZOVA/huWZHoA7oUBTUX8I0gsLTuJg/K70=,iv:DiVw3yF8EmY+IF90utX2auuCSDsWEELl2jmArzb/SzE=,tag:Aa5PRYZX0EtkWk3jEybfHg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Sp4R0FnTtCS4rQ==,iv:sY5ZGPSuiNJpiBemg6psLPC9qNJAzVnw2WM0zFjysqY=,tag:97xD7n3qQ2n2wcv1OE7xQA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qAgUd5xjuPsZ91OFBGjZbQGd6lxGkVdcdZw=,iv:umU8BA76MMK7d0PVbUKHnYJR5fNez08CWNY/zb8GOno=,tag:2eLCaWZbi6HhE4lmAmYK9Q==,type:str]
  AWS_DEFAULT_REGION: ENC[AES256_GCM,data:WBFYGff6Uc8C,iv:72OdziT7eKierUy/J3HaI8GixFdzKrHFP/GM035QJw4=,tag:gGR50KJ2Ts9IHcATQseomA==,type:str]
  MLFLOW_S3_ENDPOINT_URL: ENC[AES256_GCM,data:IlcoSg9nyaYHOrWsktkiBrF1EZoPeTjVW5TxeCtNCVg1VQcvQ2ajtPrW8AQZiQA0,iv:uG/RxvX9t5AFnCWIYXTPy4Hccd1U4GGw+2rtp0CQdAA=,tag:/WAT/poxOfCH93iYliW0Nw==,type:str]
  MLFLOW_TRACKING_URI: ENC[AES256_GCM,data:NqFBITIZ89MXyRk7Fd/9bB0qRFof0hc3i4V2EITcQpzsW7CgKfsprqchJZrDcX2+,iv:d+dzzcGE/1dlRo1yhHvRP4RyHmakRN6clvWRmi8hDYg=,tag:sz9idZK9MW9kAZPapcMfNg==,type:str]
sops:
  age:
    - recipient: age1zfl57xyrfy9nw4p6gv9kzzz593k8dv9ce3x50h3z3gfmpec6qyhs7seuqu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbW9nTUU4MjRnWnBtOWIy
        TGViV012eEgwNys2enRURCs0ZGFqcjZVQ0hJCnA1cUxZYi9yUXFaeE02TjdqNm5X
        cGN1aXQwam1NaWxyV0tLZ3dZY2o1bEEKLS0tIFR6dXoxTjZDQy9nRm1vNEdhamE4
        bDBsUThoZUdHdm5KdHhLb0tLTnZlT1kKppnDN2manjc7A6a6bmhJDcOoT6yi0eb7
        aPlYo5zmGOOmGDSNGygXko0rq29S5fnmpQuqjEB5L9srqZcTUObI/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T14:32:33Z"
  mac: ENC[AES256_GCM,data:QGYndFfnE1qbzoAjqUUkQqLrZUuOH9irdnSGo2dQpMzt7aJul0oIKCjkc0jg2FfxM/yqKDsI8UxiZ6akGwAzwFtakVTbRqY/wYKLKm9U6HhySmjw/YpVEEgU6D2J4MBJeFEJCU7tuJd2yrF+pHkPYaqY71XJewgZHC5hoeTTpHg=,iv:O7xfCbyLhdMrQlaIeW5J2L5OhDBJBCgcmVEBrjtgQnA=,tag:L004qte5pSiTU0cl64LSlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
